spring.application.name=restapi
# Database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA/Hibernate settings
# Automatically update database schema based on Java entity changes
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect